### ISSUE TITLE
Duplicate Challenge Tab

### ISSUE THREAD

**Issue by nickpops98** [NationStates/NationStatesPlusPlus#19]
With the 'Rift' theme I can see two challenge buttons. One seems to be a default NS one as when I disable NS++ it remains however the other has a different icon and sly appears when NS++ is enabled.
![image](https://cloud.githubusercontent.com/assets/10150659/5389600/6944f510-8153-11e4-8fda-a46ce58c2024.png)

**Comment by nickpops98** [comment]
Also I know it is something small but while we are on the topic of the rift navigation bar the spacing on the NS++ icons is off when compared to the default icons. The World Assembly icon has wider padding and the NSWiki icon has almost no padding. Its something little I know but it just looks a but off.

**Comment by Afforess** [comment]
@nickpops98 The rift nav bar spacing has been fixed.

**Comment by Afforess** [comment]
I am not seeing the duplicate challenge icon anymore. Did NS only briefly have the icon?

**Comment by Eluvatar** [comment]
Not all that briefly, but it has indeed been removed.

**Comment by nickpops98** [comment]
I don't think it has been removed as I can still see it. The default NS challenge button only appears when you are on someone else's nation page. If you are on your own page it does not show up.

**Comment by Afforess** [comment]
I don't see it on other nation's pages either.
